# Generated by Django 6.0.2 on 2026-02-16 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0002_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cbv.teacher'),
            preserve_default=False,
        ),
    ]
